// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5PcMfq7r9dx2I7Gz_4KZ6nqygJUz_lxE',
    appId: '1:439223915488:web:883ddfdb3709f326cf9185',
    messagingSenderId: '439223915488',
    projectId: 'chatapp-flutter-6bfcc',
    authDomain: 'chatapp-flutter-6bfcc.firebaseapp.com',
    storageBucket: 'chatapp-flutter-6bfcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaZZKYeXIy-qkRDWshyTcvAG-LJGVNVOg',
    appId: '1:439223915488:android:85c8ee11c88f29b1cf9185',
    messagingSenderId: '439223915488',
    projectId: 'chatapp-flutter-6bfcc',
    storageBucket: 'chatapp-flutter-6bfcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrNrcaxxCpRhZ7MzzY9ndFYsC9NAku-8U',
    appId: '1:439223915488:ios:e1985736944bb2becf9185',
    messagingSenderId: '439223915488',
    projectId: 'chatapp-flutter-6bfcc',
    storageBucket: 'chatapp-flutter-6bfcc.appspot.com',
    iosClientId: '439223915488-9dvnhukal6trbbknnsd7v7im2bkv7rsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrNrcaxxCpRhZ7MzzY9ndFYsC9NAku-8U',
    appId: '1:439223915488:ios:e1985736944bb2becf9185',
    messagingSenderId: '439223915488',
    projectId: 'chatapp-flutter-6bfcc',
    storageBucket: 'chatapp-flutter-6bfcc.appspot.com',
    iosClientId: '439223915488-9dvnhukal6trbbknnsd7v7im2bkv7rsd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappFirebase',
  );
}
